include: package:flutter_lints/flutter.yaml


linter:
  rules:
  prefer_const_constructors: false
  preter_final_filds: false
  use_key_in_widget_constructors: false
  prefer_const_linterals_to_create_immutables: false
  preter_const_constructors_in_immutables: false
  avoid_print: false

  